#!/bin/sh
#runit

ADDR=inet:`uname -n`:4321
RC="-ORBImplRepoAddr $ADDR -ORBNamingAddr $ADDR"

# run BOA daemon
echo "starting BOA daemon ..."
micod -ORBIIOPAddr $ADDR &
micod_pid=$!

sleep 1

# register server
echo "register name service ..."
imr create Naming shared `which nsd` \
 IDL:omg.org/CosNaming/NamingContext:1.0 $RC

echo "run event service ..."
eventd $RC &
eventd_pid=$!

# read
echo "register event service ..."
 imr create Event shared "`which eventd` $RC" \
 IDL:omg.org/SimpleEventChannelAdmin/EventChannelFactory:1.0 $RC

 sleep 1
echo "activating Event Service implementation"
imr activate Event $RC
sleep 4

echo "running consumer ..."
#./consumer $RC 2>$1 &
./consumer $RC &
consumer_pid=$!
sleep 2

echo "run supplier ..."
./supplier $RC

trap "echo 'killing apps'; kill -SIGTERM $consumer_pid $micod_pid $eventd_pid" 0
