' Gambas module file
PRIVATE myDB AS NEW Connection
PUBLIC tmpRec AS Result

PUBLIC FUNCTION connect2db() AS Boolean
  WITH myDB
    .Type = "mysql"
    .Host = "localhost"
    .Login = "bugtracker"
    .Password = "mypassword"
    .Name = "bugtracker"
  END WITH
  TRY myDB.Open
  IF ERROR THEN
    Message ("Cannot Open bugtracker:" & Error.Text)
    RETURN FALSE
  END IF
  RETURN TRUE
END

PUBLIC FUNCTION Exec(sql AS String) AS Result
   tmpRec = myDB.Exec(sql)
END

PUBLIC FUNCTION get_id (tName AS String, fName AS String, name AS String) AS Integer

  DIM sql AS String  
  sql = "select id from " & tName & 
        " where " & fName & "='" & name & "'"
  tmpRec=myDB.Exec(sql)
  RETURN tmpRec!id
END

PUBLIC SUB loadCombo (combo AS ComboBox, sql AS String)
  combo.Clear
  tmpRec = myDB.Exec(sql)
  FOR EACH tmpRec
    combo.Add (tmpRec[0])
  NEXT
END



