#!/bin/sh
#set -x

module="kiss"
device="kiss"
mode="666"

if [ -r "$MAPFILE" ]; then true; else
	echo "Please set MAPFILE in your environment and re-run this script"
	exit 1;
fi

for n in getledstate setledstate kbd_table fg_console; do
	eval $n=`grep -w $n $MAPFILE | awk '{print $1}'`
done

# invoke insmod and tell it where the globals live
/sbin/insmod -f $module getledstateP=0x$getledstate \
	                setledstateP=0x$setledstate \
	                kbd_tableP=0x$kbd_table \
	                fg_consoleP=0x$fg_console || exit 1

minor=`cat /proc/misc | awk "\\$2==\"$module\" {print \\$1}"`

rm -f /dev/${device}
mknod /dev/${device} c 10 $minor
chmod $mode  /dev/${device}






