.TH gendoor 1 "Nov. 2002" "gendoor 1.0" "Geometry Generator for Radiance"
.SH NAME
gendoor - Generate a door in Radiance format
.SH SYNOPSIS
.B gendoor
\fIdoor_material knob_material name width_in height_in door_thk_in\fR
.SH DESCRIPTION
.P
The gendoor utility generates a door of size width_in X height_in X
door_thk_in.  The door extends toward +X (from hinge edge to doorknob edge), +Z
(bottom of door to top), and +Y (thickness). It differs from genbox(1) only in the fact that
it adds doorknobs to both sides.
.P
The materials named on the command line must exist in some other part of your Radiance
scene files. The doorknob generation assumes your units are in inches, so if you are using
different units, create the door in inches first, and use xform to transform it to fit
your scene.
.P
The door has no frame. This is so you can rotate the door and frame separately, in order to model
an open or closed door. See \fBgenframe(1)\fR for a way to generate a frame.
.SH AUTHOR
Written by Anthony Kay.
.SH COPYRIGHT
This software is freeware. Use it as you like. The author does not give any warranty, 
including for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH SEE ALSO
.P
.B genframe(1),
.B genbox(1),
.B xform(1)
