.TH genframe 1 "Nov. 2002" "genframe 1.0" "Geometry Generator for Radiance"
.SH NAME
genframe - Generate a frame for a window or door in Radiance format
.SH SYNOPSIS
.B genframe [\fI-b\fR] \fImaterial name width_in height_in depth_in plank_thickness_in\fR
.SH DESCRIPTION
.P
The genframe utility generates a frame for a window or door. The frame opens in the +Y direction,
width is in +X, and height in +Z. The lower left corner of the frame is at the origin.
.TP
\fB\-b\fR
Include a bottom plank (default is a 3-sided frame for a door)
.P
The materials named on the command line must exist in some other part of your Radiance
scene files. Genframe also assumes your units are in inches, so if you are using
different units, create the door in inches first, and use xform to transform it to fit
your scene.
.SH AUTHOR
Written by Anthony Kay.
.SH COPYRIGHT
This software is freeware. Use it as you like. The author does not give any warranty, 
including for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH SEE ALSO
.P
.B xform(1)
