.TH genlog 1 "Nov. 2002" "genlog 1.0" "Geometry Generator for Radiance"
.SH NAME
genlog \- Generate a log in Radiance format
.SH SYNOPSIS
.B genlog \fB[\-c top|bottom] [\-h cut_ht] material name length diameter\fR
.SH DESCRIPTION
.P
The genlog utility generates a log. In it's simplest form, pass a material,
name, length in feet, and diameter. The resulting log will be centered on, and
follow the x\-axis.  However, the utility can also generate a cut log (for
fitting in window and door frames) by specifying the \-h and \-c options.  
.SH OPTIONS
.TP
.BI \-c " top|bottom"
Cut off the top or bottom of the log. Default is top.
.TP
.BI \-h " cut_ht"
Cut the log at a specific height from the center of the log (\-radius < cut_ht
< radius). The value 0 means cut the log down the middle. By default, the "top" is
cut off. Remember that the log is horizontal, so top and bottom refer to what would
normally be considered the "sides" of a standing tree.
.SH AUTHOR
Written by Anthony Kay.
.SH COPYRIGHT
This software is freeware. Use it as you like. The author does not give any warranty, 
including for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH SEE ALSO
.P
.B xform(1)
