.TH genwindow 1 "Nov. 2002" "genwindow 1.0" "Geometry Generator for Radiance"
.SH NAME
genwindow \- Generate a window in Radiance format
.SH SYNOPSIS
.B genwindow \fIbordermat glassmat name width_in ht_in frame_thk_in npanesx npanesz\fR
.SH DESCRIPTION
.P
The genwindow utility generates a window of size width_in inches in X, ht_in inches in Z, 
and frame_thk_in inches in Z with the lower left corner at the origin. The glass will
be split into npanesx by npanesz. Use xform to move it into place. The materials bordermat
and glassmat are used for those parts of the window respectively.
.P
The materials named on the command line must exist in some other part of your Radiance
scene files. 
.P
The window has a border, but you may want to add an extra frame. See
\fBgenframe(1)\fR for a way to generate a frame.
.SH AUTHOR
Written by Anthony Kay.
.SH COPYRIGHT
This software is freeware. Use it as you like. The author does not give any warranty, 
including for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH SEE ALSO
.P
.B genframe(1),
.B xform(1)
