insert into state (cid, sname) values (2, 'Alabama');
insert into state (cid, sname) values (2, 'Alaska');
insert into state (cid, sname) values (2, 'Arizona');
insert into state (cid, sname) values (2, 'Arkansas');
insert into state (cid, sname) values (2, 'California');
insert into state (cid, sname) values (2, 'Colorado');
insert into state (cid, sname) values (2, 'Connecticut');
insert into state (cid, sname) values (2, 'Delaware');
insert into state (cid, sname) values (2, 'Florida');
insert into state (cid, sname) values (2, 'Georgia');
insert into state (cid, sname) values (2, 'Hawaii');
insert into state (cid, sname) values (2, 'Idaho');
insert into state (cid, sname) values (2, 'Illinois');
insert into state (cid, sname) values (2, 'Indiana');
insert into state (cid, sname) values (2, 'Iowa');
insert into state (cid, sname) values (2, 'Kansas');
insert into state (cid, sname) values (2, 'Kentucky');
insert into state (cid, sname) values (2, 'Louisiana');
insert into state (cid, sname) values (2, 'Maine');
insert into state (cid, sname) values (2, 'Maryland');
insert into state (cid, sname) values (2, 'Massachusetts');
insert into state (cid, sname) values (2, 'Michigan');
insert into state (cid, sname) values (2, 'Minnesota');
insert into state (cid, sname) values (2, 'Mississippi');
insert into state (cid, sname) values (2, 'Missouri');
insert into state (cid, sname) values (2, 'Montana');
insert into state (cid, sname) values (2, 'Nebraska');
insert into state (cid, sname) values (2, 'Nevada');
insert into state (cid, sname) values (2, 'New Hampshire');
insert into state (cid, sname) values (2, 'New Jersey');
insert into state (cid, sname) values (2, 'New Mexico');
insert into state (cid, sname) values (2, 'New York');
insert into state (cid, sname) values (2, 'North Carolina');
insert into state (cid, sname) values (2, 'North Dakota');
insert into state (cid, sname) values (2, 'Ohio');
insert into state (cid, sname) values (2, 'Oklahoma');
insert into state (cid, sname) values (2, 'Oregon');
insert into state (cid, sname) values (2, 'Pennsylvania');
insert into state (cid, sname) values (2, 'Rhode Island');
insert into state (cid, sname) values (2, 'South Carolina');
insert into state (cid, sname) values (2, 'South Dakota');
insert into state (cid, sname) values (2, 'Tennessee');
insert into state (cid, sname) values (2, 'Texas');
insert into state (cid, sname) values (2, 'Utah');
insert into state (cid, sname) values (2, 'Vermont');
insert into state (cid, sname) values (2, 'Virginia');
insert into state (cid, sname) values (2, 'Washington');
insert into state (cid, sname) values (2, 'Washington, D.C.');
insert into state (cid, sname) values (2, 'West Virginia');
insert into state (cid, sname) values (2, 'Wisconsin');
insert into state (cid, sname) values (2, 'Wyoming');
