#!/bin/sh
module="sad"
device="sad"
group="wheel"
mode="664"

# invoke insmod with all arguments we got
/sbin/insmod -f $module $* || exit 1

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

rm -f /dev/${device}
mknod /dev/${device} c $major 0
mknod /dev/${device}nb c $major 1
chgrp $group /dev/${device} /dev/${device}nb
chmod $mode  /dev/${device} /dev/${device}nb






