#! /usr/bin/perl -w

use strict;

use OpenOffice::OODoc;

my $document = ooDocument( file => 'blank.sxw' );

$document->appendParagraph
(
    text    => 'Some new text',
    style   => 'Text body'
);

$document->save;

