#!/bin/sh
#
# This is part 2 of the ppp-on script. It will perform the connection
# protocol for the desired connection.
#
#exec chat						\

exec chat  -v						\
	TIMEOUT		15				\
	ABORT		'BUSY'				\
	ABORT		'NO ANSWER'			\
	ABORT		'RINGING\r\n\r\nRINGING'	\
	''		ATZ				\
	'OK-+++-OK'	ATH0				\
	TIMEOUT		90				\
	OK		'ATE0X4Q0V1&C1&D2&K3L0M0'		\
	OK		ATDT$TELEPHONE			\
	CONNECT		''				
